ptrofimov/beanstalk_console

- lib/include.php
> enhanced delete Delayed messages fixes #91

- composer.json
There were a bunch of extra spaces. Reformatted the file. Simple diff.
> Reformatted the composer.json file.

- config.php
- public/index.php
Very basic authentication, but usable.
> Added basic authentication

- Dockerfile
- README.md
- docker/apache2.conf
- fig.yml
Adding Docker support and Fig file for starting beanstalkd and console at the same time. Automated build is running
> Adding Docker and Fig support to orchestrate console and daemon

- lib/tpl/allTubes.php
- lib/tpl/modalClearTubes.php
[08-Sep-2015 09:47:45 UTC] PHP Warning:  Invalid argument supplied for foreach() in /opt/opoc/sites/beanstalk/lib/tpl/allTubes.php on line 23
[08-Sep-2015 09:47:45 UTC] PHP Stack trace:
[08-Sep-2015 09:47:45 UTC] PHP   1. {main}() /opt/opoc/sites/beanstalk/public/index.php:0
[08-Sep-2015 09:47:45 UTC] PHP   2. require_once() /opt/opoc/sites/beanstalk/public/index.php:46
[08-Sep-2015 09:47:45 UTC] PHP   3. require_once() /opt/opoc/sites/beanstalk/lib/tpl/ajax.php:1
> Error fix in allTubes.php

- config.php
- lib/include.php
- lib/tpl/ajax.php
- lib/tpl/main.php
- public/index.php
I had to use the project as a composer module and ran into some problems. 
The first problem was the use of "global" directive. Inside my project, the system does no recognized these variables. So I changed to use $GLOBALS.
The second problem I had been in the include of files. Because the use of relative paths I got some problems. I added to the path the directive `__DIR__` to force the use of the correct directory.
> Changed the global vars to $GLOBALS and fix some includes

- lib/BeanstalkInterface.class.php
- lib/tpl/modalSettings.php
- public/js/customer.js
> added base64 decoded

- lib/include.php
- lib/tpl/allTubes.php
- lib/tpl/currentTubeJobsActionsRow.php
- lib/tpl/currentTubeJobsShowcase.php
- lib/tpl/currentTubeSearchResults.php
- lib/tpl/main.php
- lib/tpl/sampleJobsManage.php
> fixed urlencode issue

- lib/tpl/currentTubeJobsShowcase.php
After merging this there will be better job age visibility in tube view.
Example:
> Show job age in human readable format

- lib/tpl/currentTubeJobsShowcase.php
Addition to #137 
Will not show days: 0, hours: 0 etc..
> Do not show job age row when row value is zero

- lib/tpl/currentTubeJobsShowcase.php
> Show human-friendly info for several tube stats

- lib/include.php
- lib/tpl/main.php
> Server names in nav

- lib/tpl/main.php
Resolves https://github.com/ptrofimov/beanstalk_console/issues/144
> Add detail to page titles

- lib/include.php
Fixes #161.
Now the last job ID to use for searching jobs is correctly calculated across the whole server. Indeed, the maximum job ID should be the sum of the ready, reserved, delayed and buried jobs plus the cumulative number of delete commands.
> Fixes search by calculating maximum job ID

- lib/tpl/main.php
Combine the power of #160 and #157 (both of which were great by themselves!)
> Use pretty server label in HTML page title

- public/js/customer.js
> Fixed auto-refresh on summary page

- Dockerfile
Noticed that base image does not have latest security patches installed. This pull request adds latest patches.
> Addition to Dockerfile to get latest security patches.

- public/css/customer.css
Just like buried ones, adding some css to also highlight delayed ones. I picked some complementing colours, feel free to edit.
Perhaps down the line these could be config values (enable/disable and what colours).
> Highlight delayed jobs

- lib/tpl/main.php
> Error in PHP8

- lib/tpl/main.php
- lib/tpl/serversList.php
Fix issue XSS can trigger in name host
Disclosure : https://huntr.dev/bounties/5f41b182-dda2-4c6f-9668-2a9afaed53af/
> applying htmlspecialchars for sanitization output

- lib/tpl/currentTubeJobsActionsRow.php
Tested: Local browser testing.
> [style-fix] Fix button group broken in Chrome UI.

- lib/BeanstalkInterface.class.php
- lib/include.php
- lib/tpl/main.php
- public/css/customer.css
- public/js/customer.js
> add tube filter + improves mass move
